### ISSUE TITLE
BUG: Sidebar in Game Rules Page

### ISSUE THREAD

**Issue by AnanyaJain25** [EternoSeeker/gameoflife#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is no back button avaialable once you reach game rules section. Sidebar should be avaialable to navigate through other pages.

![Screenshot 2024-05-28 192218](https://github.com/EternoSeeker/gameoflife/assets/136808696/01830277-eac1-40a4-837b-3ac4db794e16)
This sidebar should remain intact
![Screenshot 2024-05-28 192232](https://github.com/EternoSeeker/gameoflife/assets/136808696/e3c7689e-2f99-4771-a7e5-606bd4cfba7a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
Sure you can work on it

**Comment by adityas-github** [comment]
Instead of adding an in-game rules page sidebar, we can add a button in the top left corner that will lead to the home page, where the user can access other features. This approach will reduce the extra code required for the sidebar and also provide more space on the rules page, making it more visually appealing to the user.
